const fs = require("fs");
const axios = require("axios");

let keywords = [
  "bride dress where",
  "bridesmaid dress vs maid of honor",
  "grace kelly wedding dress where is it",
  "how far in advance do you pick a wedding dress",
  "how to choose a wedding dress",
  "how to display wedding dress",
  "princess diana wedding dress where is it",
  "wedding dress affordable",
  "wedding dress alexandria va",
  "wedding dress alterations",
  "wedding dress alterations alexandria va",
  "wedding dress alterations cost",
  "wedding dress alterations dc",
  "wedding dress alterations frederick md",
  "wedding dress alterations near me",
  "wedding dress alterations when",
  "wedding dress and boots",
  "wedding dress and converse",
  "wedding dress and cowboy boots",
  "wedding dress and jacket",
  "wedding dress and shoes",
  "wedding dress and sneakers",
  "wedding dress and suit",
  "wedding dress and tuxedo",
  "wedding dress and veil",
  "wedding dress bag",
  "wedding dress ball gown",
  "wedding dress belts",
  "wedding dress boutiques",
  "wedding dress boutiques near me",
  "wedding dress box",
  "wedding dress brands",
  "wedding dress bustle",
  "wedding dress can be altered",
  "wedding dress can't decide",
  "wedding dress canada",
  "wedding dress canada online",
  "wedding dress canberra",
  "wedding dress cancellation rights",
  "wedding dress cancer charity",
  "wedding dress candle",
  "wedding dress canton",
  "wedding dress canyon tx",
  "wedding dress cleaning",
  "wedding dress cleaning and preservation",
  "wedding dress code guide",
  "wedding dress codes",
  "wedding dress consignment",
  "wedding dress consignment near me",
  "wedding dress consignment shops near me",
  "wedding dress cost",
  "wedding dress dc",
  "wedding dress designer online",
  "wedding dress designers",
  "wedding dress detachable skirt",
  "wedding dress donation",
  "wedding dress drawing",
  "wedding dress dream meaning death",
  "wedding dress dry cleaning",
  "wedding dress elegant",
  "wedding dress elopement",
  "wedding dress embellishments",
  "wedding dress embroidery",
  "wedding dress english lyrics",
  "wedding dress etiquette",
  "wedding dress etsy",
  "wedding dress expo",
  "wedding dress fabric",
  "wedding dress finder",
  "wedding dress for courthouse",
  "wedding dress for groom",
  "wedding dress for guest",
  "wedding dress for older bride",
  "wedding dress for rent",
  "wedding dress for sale",
  "wedding dress for short women",
  "wedding dress for women",
  "wedding dress fredericksburg va",
  "wedding dress garment bag",
  "wedding dress georgetown",
  "wedding dress giveaway",
  "wedding dress green",
  "wedding dress guest",
  "wedding dress guest fall",
  "wedding dress guest winter",
  "wedding dress guide",
  "wedding dress halter",
  "wedding dress halter neck",
  "wedding dress hanger",
  "wedding dress hanger with name",
  "wedding dress heels",
  "wedding dress high neck",
  "wedding dress holder",
  "wedding dress house reviews",
  "wedding dress how far in advance",
  "wedding dress how long",
  "wedding dress how much",
  "wedding dress how much does it cost",
  "wedding dress how to bustle",
  "wedding dress how to choose",
  "wedding dress how to make",
  "wedding dress how to store",
  "wedding dress howell mi",
  "wedding dress ideas",
  "wedding dress images",
  "wedding dress in dc",
  "wedding dress in fredericksburg va",
  "wedding dress in new york",
  "wedding dress in spanish",
  "wedding dress indian",
  "wedding dress inspiration",
  "wedding dress is a dream",
  "wedding dress is long",
  "wedding dress is pink",
  "wedding dress is tight",
  "wedding dress is too big",
  "wedding dress is too short",
  "wedding dress is too small",
  "wedding dress is white",
  "wedding dress israel",
  "wedding dress istanbul",
  "wedding dress jacket",
  "wedding dress jacket ideas",
  "wedding dress jacket lace",
  "wedding dress jenny yoo",
  "wedding dress jewelry",
  "wedding dress jobs",
  "wedding dress jumpsuits",
  "wedding dress justin alexander",
  "wedding dress karen willis holmes",
  "wedding dress kdrama",
  "wedding dress keepsake",
  "wedding dress keepsake box",
  "wedding dress keepsake ideas",
  "wedding dress kleinfeld",
  "wedding dress knee length",
  "wedding dress korean",
  "wedding dress kpop",
  "wedding dress lace",
  "wedding dress lace sleeves",
  "wedding dress like bella swan",
  "wedding dress like cinderella",
  "wedding dress like grace kelly",
  "wedding dress like hailey bieber",
  "wedding dress like jenny from forrest gump",
  "wedding dress like kate middleton",
  "wedding dress like meghan markle",
  "wedding dress like pippa middleton",
  "wedding dress long sleeve",
  "wedding dress long sleeve lace",
  "wedding dress long train",
  "wedding dress low back",
  "wedding dress lulus",
  "wedding dress lyrics",
  "wedding dress magazines",
  "wedding dress maker",
  "wedding dress makers near me",
  "wedding dress material",
  "wedding dress mermaid",
  "wedding dress mermaid style",
  "wedding dress modest",
  "wedding dress movie",
  "wedding dress near me",
  "wedding dress near me cheap",
  "wedding dress near me for rent",
  "wedding dress near me now",
  "wedding dress necklace",
  "wedding dress necklines",
  "wedding dress no train",
  "wedding dress nordstrom",
  "wedding dress not white",
  "wedding dress off the shoulder",
  "wedding dress old town alexandria",
  "wedding dress on a budget",
  "wedding dress online",
  "wedding dress orange",
  "wedding dress order online",
  "wedding dress order time",
  "wedding dress organza",
  "wedding dress origin",
  "wedding dress orlando",
  "wedding dress ornaments",
  "wedding dress outlet",
  "wedding dress outlet near me",
  "wedding dress overlay",
  "wedding dress overskirt",
  "wedding dress patterns",
  "wedding dress places near me",
  "wedding dress plus size",
  "wedding dress preservation",
  "wedding dress preservation box",
  "wedding dress preservation near me",
  "wedding dress prices",
  "wedding dress princess",
  "wedding dress quilt",
  "wedding dress quilt ideas",
  "wedding dress quiz",
  "wedding dress quiz buzzfeed",
  "wedding dress quiz for body type",
  "wedding dress quiz free",
  "wedding dress quiz the knot",
  "wedding dress quotes",
  "wedding dress removable skirt",
  "wedding dress rental",
  "wedding dress rental dc",
  "wedding dress rental maryland",
  "wedding dress rental near me",
  "wedding dress resale",
  "wedding dress resale sites",
  "wedding dress restoration",
  "wedding dress serena williams",
  "wedding dress shapes explained",
  "wedding dress shoes",
  "wedding dress shops",
  "wedding dress shops alexandria va",
  "wedding dress shops dc",
  "wedding dress shops near me",
  "wedding dress shops washington",
  "wedding dress sleeves",
  "wedding dress styles",
  "wedding dress taeyang",
  "wedding dress tailor",
  "wedding dress tailor near me",
  "wedding dress that is casual",
  "wedding dress timeline",
  "wedding dress to baptism gown",
  "wedding dress to cocktail dress",
  "wedding dress to rent",
  "wedding dress to where",
  "wedding dress too small",
  "wedding dress top",
  "wedding dress top styles",
  "wedding dress topper",
  "wedding dress topper long sleeve",
  "wedding dress train",
  "wedding dress trends 2023",
  "wedding dress types",
  "wedding dress under 100",
  "wedding dress under 1000",
  "wedding dress under 200",
  "wedding dress under 500",
  "wedding dress undergarments",
  "wedding dress united airlines",
  "wedding dress up games",
  "wedding dress used",
  "wedding dress v neck",
  "wedding dress veil",
  "wedding dress vendors",
  "wedding dress venues near me",
  "wedding dress vera wang",
  "wedding dress vintage",
  "wedding dress vintage style",
  "wedding dress vivienne westwood",
  "wedding dress vs body type",
  "wedding dress vs bridal gown",
  "wedding dress vs gown",
  "wedding dress vs prom dress",
  "wedding dress vs reception dress",
  "wedding dress vs street size",
  "wedding dress was",
  "wedding dress washington",
  "wedding dress washington dc",
  "wedding dress websites",
  "wedding dress what is",
  "wedding dress what to do after",
  "wedding dress whatsapp group link",
  "wedding dress when pregnant",
  "wedding dress when to buy",
  "wedding dress where to buy",
  "wedding dress where to start",
  "wedding dress white",
  "wedding dress who pays",
  "wedding dress wholesale",
  "wedding dress wholesale distributors",
  "wedding dress wholesale near me",
  "wedding dress wholesale suppliers",
  "wedding dress wholesale turkey",
  "wedding dress wholesale uk",
  "wedding dress why white",
  "wedding dress will suit me",
  "wedding dress willa",
  "wedding dress willowby",
  "wedding dress with cape",
  "wedding dress with detachable skirt",
  "wedding dress with flowers",
  "wedding dress with gloves",
  "wedding dress with lace sleeves",
  "wedding dress with pockets",
  "wedding dress with sleeves",
  "wedding dress with slit",
  "wedding dress without boning",
  "wedding dress without bustle",
  "wedding dress without lace",
  "wedding dress without person",
  "wedding dress without sleeves",
  "wedding dress without train",
  "wedding dress without train uk",
  "wedding dress without veil",
  "wedding dress xl",
  "wedding dress xs",
  "wedding dress xxs",
  "wedding dress yellow",
  "wedding dress yellowing clean",
  "wedding dress yes to the dress",
  "wedding dress yesstyle",
  "wedding dress you can dance in",
  "wedding dress you can wear a bra with",
  "wedding dress you can wear again",
  "wedding dress youtube",
  "wedding dress zara",
  "wedding dress zero two",
  "wedding dress zipper",
  "wedding dress zipper extender",
  "wedding dress zipper replacement",
  "wedding dress zodiac",
  "wedding dress zodiac sign",
  "wedding dress zuhair murad",
  "wedding dresses",
  "wedding dresses alexandria va",
  "wedding dresses near me",
  "wedding dresses near me affordable",
  "wedding dresses near me plus size",
  "wedding dresses washington",
  "wedding dresses williamsburg va",
  "wedding is dress code",
  "what is the most popular type of wedding dress",
  "what makes a wedding dress a wedding dress",
  "what to do with a wedding dress when the wedding is cancelled",
  "when should i find my wedding dress",
  "when should you have your wedding dress",
  "when wedding dress shopping",
  "where can i design my own wedding dress",
  "which wedding dress designer",
  "which wedding dress quiz",
  "why is a wedding dress so important",
  "why wedding dress",
  "why wedding dress long",
  "why wedding dress train"
];

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  for await (keyword of keywords) {
    console.log(keyword);

    try {
      let fetchUrl = `https://suggest.johnmurch.com/google/search?q=${encodeURIComponent(
        keyword
      )}`;
      console.log("url", fetchUrl);
      const res = await axios.get(fetchUrl);
      console.log("status", res.status);
      let data = JSON.parse(JSON.stringify(res.data));
      let queries = data.queries;
      let payload = {
        keyword: keyword,
        queries: queries
      };
      // console.log(JSON.stringify(payload));
      fs.writeFileSync(`./data/${keyword}.json`, JSON.stringify(payload));
      await sleep(2000);
      // break;
    } catch (e) {
      console.log("CAUGHT API DOWN", e);
      process.exit(0);
    }
  }
}

main();
